import type { MetadataRoute } from 'next';
import { SITE_CONFIG } from '@/lib/config';
import { createServerSupabaseClient } from '@/lib/supabase/server';

/**
 * Dynamic /sitemap.xml for shopifind.app — generated by Next.js 13+
 * convention from src/app/sitemap.ts.
 *
 * Cache strategy: ISR with a 1-hour wall-clock revalidation. The sitemap
 * reflects "stock flips every few hours for masterled" + "collections are
 * curated roughly weekly" — 1h is short enough to capture stock changes,
 * long enough to avoid hammering Supabase on every Googlebot fetch
 * (Google re-fetches sitemap periodically on its own schedule anyway).
 *
 * If you ever want CACHE-BUSTING without waiting for ISR: edit any field
 * of this file and re-deploy to /scratch/ the cache or hit the route
 * with a HEAD request to force re-render.
 *
 * Site URL: declared once in src/lib/config.ts so staging and prod
 * stay in sync.
 *
 * Pagination handling: per Google guidelines, only CANONICAL URLs
 * (page=1 default) go in the sitemap. /explore/<niche>?page=2 etc. are
 * client-side navigations from <Link rel="next"> / Pagination component,
 * not separate indexable pages.
 */
export const revalidate = 3600; // 1h ISR — see comment above.

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = SITE_CONFIG.url.replace(/\/+$/, '');
  const today = new Date();
  const sb = createServerSupabaseClient();

  // ---- 1. Static routes ----
  const routes: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: today,
      changeFrequency: 'daily',
      priority: 1.0,
    },
    // /explore/<primaryNiche>: the hub pages. Highest priority below
    // the home, they're the SEO entry point for the 4 verticals.
    ...SITE_CONFIG.primaryNiches.map((niche) => ({
      url: `${baseUrl}/explore/${niche}`,
      lastModified: today,
      changeFrequency: 'daily' as const,
      priority: 0.9,
    })),
  ];

  // ---- 2. Editorial collections (curated capsules) ----
  // Power-store pages — they convert browsers into buyers via the
  // editorial framing. Monthly changeFrequency because they're curated,
  // not data-driven.
  const collectionsRes = await sb
    .from('editorial_collections')
    .select('slug, published_at')
    .eq('published', true);

  if (collectionsRes.error) {
    console.error('[sitemap] editorial_collections read failed:', collectionsRes.error.message);
  } else {
    const rows = (collectionsRes.data ?? []) as Array<{
      slug: string;
      published_at: string | null;
    }>;
    for (const c of rows) {
      routes.push({
        url: `${baseUrl}/collections/${c.slug}`,
        lastModified: c.published_at ? new Date(c.published_at) : today,
        changeFrequency: 'monthly',
        priority: 0.8,
      });
    }
  }

  // ---- 3. Products (in_stock=true) ----
  // EXPLICIT field projection — DO NOT use select('*') here.
  // products table carries descriptions (~2KB each), attributes, and
  // other heavy JSON columns. select('*') on 1441 rows pulls ~3MB into
  // Vercel's Edge function memory just to throw it away after we read
  // 2 columns.
  //
  // updated_at drives changeFrequency: Google re-crawls when our
  // sitemap signals this date advanced since last fetch, which is what
  // we want for stock flips.
  const productsRes = await sb
    .from('products')
    .select('slug, updated_at')
    .eq('in_stock', true);

  if (productsRes.error) {
    console.error('[sitemap] products read failed:', productsRes.error.message);
  } else {
    const rows = (productsRes.data ?? []) as Array<{
      slug: string;
      updated_at: string | null;
    }>;
    for (const p of rows) {
      routes.push({
        url: `${baseUrl}/product/${p.slug}`,
        lastModified: p.updated_at ? new Date(p.updated_at) : today,
        changeFrequency: 'weekly',
        priority: 0.6,
      });
    }
  }

  return routes;
}
