-- ============================================================================
-- Shopifind — relational price history and price alerts foundation.
-- Run after 00000000000002_add_iluminacion_niche.sql.
-- Idempotent: safe to re-run.
-- ============================================================================

-- Immutable change log. A product trigger records only price, currency or
-- availability changes, so an ingest that upserts an unchanged row creates no
-- duplicate history entry.
CREATE TABLE IF NOT EXISTS price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  price_cents INT NOT NULL CHECK (price_cents >= 0),
  currency TEXT NOT NULL DEFAULT 'EUR' CHECK (char_length(currency) = 3),
  in_stock BOOLEAN NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_price_history_product_observed
  ON price_history(product_id, observed_at DESC);

ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public_read_price_history" ON price_history;
CREATE POLICY "public_read_price_history" ON price_history
  FOR SELECT USING (TRUE);

CREATE OR REPLACE FUNCTION record_product_price_history()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO price_history (product_id, price_cents, currency, in_stock, observed_at)
    VALUES (NEW.id, NEW.price_cents, NEW.currency, NEW.in_stock, NOW());
  ELSIF OLD.price_cents IS DISTINCT FROM NEW.price_cents
    OR OLD.currency IS DISTINCT FROM NEW.currency
    OR OLD.in_stock IS DISTINCT FROM NEW.in_stock
  THEN
    INSERT INTO price_history (product_id, price_cents, currency, in_stock, observed_at)
    VALUES (NEW.id, NEW.price_cents, NEW.currency, NEW.in_stock, NOW());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_products_price_history ON products;
CREATE TRIGGER trg_products_price_history
  AFTER INSERT OR UPDATE OF price_cents, currency, in_stock ON products
  FOR EACH ROW EXECUTE FUNCTION record_product_price_history();

-- Baseline snapshot for products that existed before the trigger. Re-running
-- the migration does not add another baseline for an already-known product.
INSERT INTO price_history (product_id, price_cents, currency, in_stock, observed_at)
SELECT
  p.id,
  p.price_cents,
  p.currency,
  p.in_stock,
  COALESCE(p.last_seen_at, p.updated_at, NOW())
FROM products p
WHERE NOT EXISTS (
  SELECT 1 FROM price_history h WHERE h.product_id = p.id
);

-- One configurable alert per user/product. Changing mode updates this row;
-- delivery idempotence lives separately in price_alert_deliveries.
CREATE TABLE IF NOT EXISTS price_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  mode TEXT NOT NULL DEFAULT 'any_drop'
    CHECK (mode IN ('any_drop', 'target_price', 'percentage_drop')),
  baseline_price_cents INT NOT NULL CHECK (baseline_price_cents >= 0),
  baseline_currency TEXT NOT NULL CHECK (char_length(baseline_currency) = 3),
  target_price_cents INT CHECK (target_price_cents >= 0),
  percentage_drop SMALLINT CHECK (percentage_drop BETWEEN 1 AND 99),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_evaluated_history_id BIGINT REFERENCES price_history(id) ON DELETE SET NULL,
  last_notified_price_cents INT CHECK (last_notified_price_cents >= 0),
  last_notified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT price_alerts_user_product_unique UNIQUE (user_id, product_id),
  CONSTRAINT price_alerts_mode_fields_check CHECK (
    (mode = 'any_drop' AND target_price_cents IS NULL AND percentage_drop IS NULL)
    OR (mode = 'target_price' AND target_price_cents IS NOT NULL AND percentage_drop IS NULL)
    OR (mode = 'percentage_drop' AND target_price_cents IS NULL AND percentage_drop IS NOT NULL)
  )
);

-- Upgrade path for an earlier local draft of this migration. Currency is part
-- of the alert reference: comparing cents from different currencies can cause
-- a false notification.
ALTER TABLE price_alerts
  ADD COLUMN IF NOT EXISTS baseline_currency TEXT;
UPDATE price_alerts a
SET baseline_price_cents = p.price_cents,
    baseline_currency = p.currency,
    active = CASE WHEN a.mode = 'target_price' THEN FALSE ELSE a.active END,
    last_evaluated_history_id = (
      SELECT MAX(h.id) FROM price_history h WHERE h.product_id = a.product_id
    ),
    last_notified_price_cents = NULL,
    last_notified_at = NULL
FROM products p
WHERE a.product_id = p.id
  AND a.baseline_currency IS NULL;
UPDATE price_alerts SET baseline_currency = 'EUR' WHERE baseline_currency IS NULL;
ALTER TABLE price_alerts ALTER COLUMN baseline_currency SET NOT NULL;
ALTER TABLE price_alerts
  DROP CONSTRAINT IF EXISTS price_alerts_baseline_currency_check;
ALTER TABLE price_alerts
  ADD CONSTRAINT price_alerts_baseline_currency_check
  CHECK (char_length(baseline_currency) = 3);

CREATE INDEX IF NOT EXISTS idx_price_alerts_active_product
  ON price_alerts(product_id) WHERE active = TRUE;
CREATE INDEX IF NOT EXISTS idx_price_alerts_user_active
  ON price_alerts(user_id, updated_at DESC) WHERE active = TRUE;

DROP TRIGGER IF EXISTS trg_price_alerts_updated_at ON price_alerts;
CREATE TRIGGER trg_price_alerts_updated_at
  BEFORE UPDATE ON price_alerts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE price_alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "price_alerts_owner_all" ON price_alerts;
CREATE POLICY "price_alerts_owner_all" ON price_alerts
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Outbox/delivery ledger. The unique alert/history pair is the hard guarantee
-- that retries cannot email the same observed price change twice.
CREATE TABLE IF NOT EXISTS price_alert_deliveries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id UUID NOT NULL REFERENCES price_alerts(id) ON DELETE CASCADE,
  price_history_id BIGINT NOT NULL REFERENCES price_history(id) ON DELETE CASCADE,
  reference_price_cents INT NOT NULL CHECK (reference_price_cents >= 0),
  reference_currency TEXT NOT NULL CHECK (char_length(reference_currency) = 3),
  status TEXT NOT NULL DEFAULT 'pending',
  provider_message_id TEXT,
  error_message TEXT,
  attempt_count INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  attempted_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  CONSTRAINT price_alert_deliveries_event_unique
    UNIQUE (alert_id, price_history_id)
);

ALTER TABLE price_alert_deliveries
  ADD COLUMN IF NOT EXISTS reference_price_cents INT CHECK (reference_price_cents >= 0);
ALTER TABLE price_alert_deliveries
  ADD COLUMN IF NOT EXISTS reference_currency TEXT;
ALTER TABLE price_alert_deliveries
  DROP CONSTRAINT IF EXISTS price_alert_deliveries_status_check;
UPDATE price_alert_deliveries d
SET status = 'skipped',
    error_message = 'migration_missing_currency_reference',
    reference_price_cents = COALESCE(
      d.reference_price_cents,
      a.baseline_price_cents
    ),
    reference_currency = COALESCE(d.reference_currency, a.baseline_currency)
FROM price_alerts a
WHERE d.alert_id = a.id
  AND (d.reference_price_cents IS NULL OR d.reference_currency IS NULL);
UPDATE price_alert_deliveries
SET reference_price_cents = 0
WHERE reference_price_cents IS NULL;
UPDATE price_alert_deliveries
SET reference_currency = 'EUR'
WHERE reference_currency IS NULL;
ALTER TABLE price_alert_deliveries
  ALTER COLUMN reference_price_cents SET NOT NULL,
  ALTER COLUMN reference_currency SET NOT NULL;
ALTER TABLE price_alert_deliveries
  DROP CONSTRAINT IF EXISTS price_alert_deliveries_reference_currency_check;
ALTER TABLE price_alert_deliveries
  ADD CONSTRAINT price_alert_deliveries_reference_currency_check
  CHECK (char_length(reference_currency) = 3);

ALTER TABLE price_alert_deliveries
  ADD CONSTRAINT price_alert_deliveries_status_check
  CHECK (status IN ('pending', 'processing', 'sent', 'failed', 'skipped'));

CREATE INDEX IF NOT EXISTS idx_price_alert_deliveries_pending
  ON price_alert_deliveries(created_at)
  WHERE status IN ('pending', 'failed');

ALTER TABLE price_alert_deliveries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "price_alert_deliveries_owner_read" ON price_alert_deliveries;
CREATE POLICY "price_alert_deliveries_owner_read" ON price_alert_deliveries
  FOR SELECT USING (
    EXISTS (
      SELECT 1
      FROM price_alerts a
      WHERE a.id = price_alert_deliveries.alert_id
        AND a.user_id = auth.uid()
    )
  );

-- No client INSERT/UPDATE policies on price_history or deliveries. Product
-- ingests and the future cron use service-role; users only manage their own
-- price_alerts rows through RLS-aware server actions.
